// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Travel.Models;

namespace Travel.Solution.Migrations
{
    [DbContext(typeof(TravelContext))]
    [Migration("20191028234426_ExtraSeeds")]
    partial class ExtraSeeds
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Travel.Models.Destination", b =>
                {
                    b.Property<int>("DestinationId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<int>("Rating");

                    b.Property<string>("Review");

                    b.HasKey("DestinationId");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            DestinationId = 2,
                            City = "Oakland",
                            Country = "USA",
                            Rating = 2,
                            Review = "Sunny, mild, rough"
                        },
                        new
                        {
                            DestinationId = 3,
                            City = "Sayulita",
                            Country = "Mexico",
                            Rating = 4,
                            Review = "Crowded and touristy, but still beautiful and warm."
                        },
                        new
                        {
                            DestinationId = 4,
                            City = "Santiago",
                            Country = "Chile",
                            Rating = 3,
                            Review = "Busy, a little smoggy, gorgeous mountains"
                        },
                        new
                        {
                            DestinationId = 5,
                            City = "Lagos",
                            Country = "Nigeria",
                            Rating = 3,
                            Review = "Vast, expansive"
                        },
                        new
                        {
                            DestinationId = 6,
                            City = "Cairo",
                            Country = "Eqypt",
                            Rating = 5,
                            Review = "So many incredible places to visit"
                        },
                        new
                        {
                            DestinationId = 7,
                            City = "Bangkok",
                            Country = "Thailand",
                            Rating = 4,
                            Review = "Humid, noisy, delicious food"
                        },
                        new
                        {
                            DestinationId = 8,
                            City = "Tokyo",
                            Country = "Japan",
                            Rating = 5,
                            Review = "Bright, bustling, exciting"
                        },
                        new
                        {
                            DestinationId = 9,
                            City = "Berlin",
                            Country = "Germany",
                            Rating = 4,
                            Review = "Excellent vegetarian options"
                        },
                        new
                        {
                            DestinationId = 10,
                            City = "Ashgabat",
                            Country = "Turkmenistan",
                            Rating = 2,
                            Review = "Dry, drought, rough"
                        },
                        new
                        {
                            DestinationId = 11,
                            City = "Antananarivo",
                            Country = "Madagascar",
                            Rating = 2,
                            Review = "High crime, politically unstable"
                        },
                        new
                        {
                            DestinationId = 12,
                            City = "Brazzaville",
                            Country = "Congo",
                            Rating = 2,
                            Review = "Beautiful but corrupt"
                        },
                        new
                        {
                            DestinationId = 13,
                            City = "Melbourne",
                            Country = "Australia",
                            Rating = 4,
                            Review = "Gorgeous with fantastic food"
                        },
                        new
                        {
                            DestinationId = 14,
                            City = "Chicago",
                            Country = "USA",
                            Rating = 4,
                            Review = "Windy, great pizza"
                        },
                        new
                        {
                            DestinationId = 15,
                            City = "Vancouver",
                            Country = "Canada",
                            Rating = 3,
                            Review = "Diverse, denim"
                        },
                        new
                        {
                            DestinationId = 16,
                            City = "Glasgow",
                            Country = "Scotland",
                            Rating = 3,
                            Review = "Bland food, gorgeous nature"
                        },
                        new
                        {
                            DestinationId = 17,
                            City = "Mexico City",
                            Country = "Mexico",
                            Rating = 4,
                            Review = "Bustling, bright, crowded"
                        },
                        new
                        {
                            DestinationId = 18,
                            City = "Male",
                            Country = "Maldives",
                            Rating = 3,
                            Review = "Tropical, prone to flooding"
                        },
                        new
                        {
                            DestinationId = 19,
                            City = "Frankfurt",
                            Country = "Germany",
                            Rating = 4,
                            Review = "Sausages everywhere"
                        },
                        new
                        {
                            DestinationId = 20,
                            City = "Sao Paulo",
                            Country = "Brazil",
                            Rating = 3,
                            Review = "Big. Good nightlife"
                        },
                        new
                        {
                            DestinationId = 21,
                            City = "Guadalajara",
                            Country = "Mexico",
                            Rating = 4,
                            Review = "Lots of markets, great food, good weather"
                        },
                        new
                        {
                            DestinationId = 22,
                            City = "Puerto Vallarta",
                            Country = "Mexico",
                            Rating = 3,
                            Review = "Beaches, resorts"
                        },
                        new
                        {
                            DestinationId = 23,
                            City = "Munich",
                            Country = "Germany",
                            Rating = 3,
                            Review = "Laderhosen"
                        },
                        new
                        {
                            DestinationId = 24,
                            City = "Shanghai",
                            Country = "China",
                            Rating = 3,
                            Review = "Insanely crowded, spicy food"
                        },
                        new
                        {
                            DestinationId = 25,
                            City = "Xi'an",
                            Country = "China",
                            Rating = 2,
                            Review = "Crowded"
                        },
                        new
                        {
                            DestinationId = 26,
                            City = "Kyoto",
                            Country = "Japan",
                            Rating = 5,
                            Review = "Cherry blossoms, temples, beautiful"
                        },
                        new
                        {
                            DestinationId = 27,
                            City = "Valletta",
                            Country = "Malta",
                            Rating = 3,
                            Review = "Cool"
                        },
                        new
                        {
                            DestinationId = 28,
                            City = "Juneau",
                            Country = "USA",
                            Rating = 5,
                            Review = "The most beautiful place, ever"
                        },
                        new
                        {
                            DestinationId = 29,
                            City = "Inn Wa",
                            Country = "Burma",
                            Rating = 4,
                            Review = "Great food"
                        },
                        new
                        {
                            DestinationId = 30,
                            City = "Kiev",
                            Country = "Ukraine",
                            Rating = 1,
                            Review = "Violent, dangerous, terrible"
                        },
                        new
                        {
                            DestinationId = 31,
                            City = "Kingston",
                            Country = "Jamaica",
                            Rating = 4,
                            Review = "Mellow, warm, colorful, crowded"
                        },
                        new
                        {
                            DestinationId = 32,
                            City = "Ocho Rios",
                            Country = "Jamaica",
                            Rating = 3,
                            Review = "Humid, lively"
                        },
                        new
                        {
                            DestinationId = 33,
                            City = "Limon",
                            Country = "Costa Rica",
                            Rating = 5,
                            Review = "Beautiful"
                        },
                        new
                        {
                            DestinationId = 34,
                            City = "San Jose",
                            Country = "Costa Rica",
                            Rating = 1,
                            Review = "Lots of people, lots to do"
                        },
                        new
                        {
                            DestinationId = 35,
                            City = "Iquique",
                            Country = "Chile",
                            Rating = 3,
                            Review = "Tons of buildings"
                        },
                        new
                        {
                            DestinationId = 36,
                            City = "Pucon",
                            Country = "Chile",
                            Rating = 2,
                            Review = "Big mountain"
                        },
                        new
                        {
                            DestinationId = 37,
                            City = "Valparaiso",
                            Country = "Chile",
                            Rating = 3,
                            Review = "Beach"
                        },
                        new
                        {
                            DestinationId = 38,
                            City = "Osaka",
                            Country = "Japan",
                            Rating = 2,
                            Review = "Cold. So cold"
                        },
                        new
                        {
                            DestinationId = 39,
                            City = "Odesa",
                            Country = "Ukraine",
                            Rating = 2,
                            Review = "A little scary. Old and cold"
                        },
                        new
                        {
                            DestinationId = 40,
                            City = "Gothenburg",
                            Country = "Sweden",
                            Rating = 4,
                            Review = "Nice bridge"
                        },
                        new
                        {
                            DestinationId = 41,
                            City = "Stockholm",
                            Country = "Sweden",
                            Rating = 1,
                            Review = "Expensive and snowy"
                        },
                        new
                        {
                            DestinationId = 42,
                            City = "Kathmandu",
                            Country = "Nepal",
                            Rating = 5,
                            Review = "Temples, spiritual"
                        },
                        new
                        {
                            DestinationId = 43,
                            City = "Pokhara",
                            Country = "Nepal",
                            Rating = 4,
                            Review = "Expansive natural views"
                        },
                        new
                        {
                            DestinationId = 44,
                            City = "Batman",
                            Country = "Turkey",
                            Rating = 3,
                            Review = "Great Bruce Wayne"
                        },
                        new
                        {
                            DestinationId = 45,
                            City = "Istanbul",
                            Country = "Turkey",
                            Rating = 2,
                            Review = "Historic, lots of sights to see"
                        },
                        new
                        {
                            DestinationId = 46,
                            City = "Ulaanbaatar",
                            Country = "Mongolia",
                            Rating = 3,
                            Review = "Most colorful flag"
                        },
                        new
                        {
                            DestinationId = 47,
                            City = "St Petersburg",
                            Country = "Russia",
                            Rating = 3,
                            Review = "Stark. Cold"
                        },
                        new
                        {
                            DestinationId = 48,
                            City = "Moscow",
                            Country = "Russia",
                            Rating = 2,
                            Review = "Vast"
                        },
                        new
                        {
                            DestinationId = 49,
                            City = "Kazan",
                            Country = "Russia",
                            Rating = 5,
                            Review = "Blue Skies"
                        },
                        new
                        {
                            DestinationId = 50,
                            City = "Tulum",
                            Country = "Mexico",
                            Rating = 5,
                            Review = "Beaches, caves to explore"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
